# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


[[main]]
weight = 2
identifier = "files"
name = "法律法规"
url = "/categories/files/"
[main.params]
icon = "book"

[[main]]
weight = 3
identifier = "sb189"
name = "SB 189"
url = "/sb189/"

[main.params]
icon = "law-svgrepo-com"

[[main]]
weight = 3
identifier = "useless-gov"
name = "管局渎职"
url = "/useless-gov/"

[main.params]
icon = "handcuffs-svgrepo-com"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"
